title: Shaswat Gupta
# subtitle: MSc CS ETH Zurich | IIT Bombay (Rank 1, Gold Medalist) | ML Engineer | Ex-World Bank, Budweiser
subtitle: ETH Zurich | IIT Bombay Rank 1, Gold Medalist | ML Engineer
description: Professional portfolio and curated course notes
url: https://Shaswat-G.github.io
repository: Shaswat-G/Shaswat-G.github.io
logo: /assets/images/logo.png

# Theme config
# theme: minimal-mistakes-jekyll
remote_theme: "mmistakes/minimal-mistakes"
minimal_mistakes_skin: "air" # "default" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"

# Site settings
locale: "en-US"

# lunr:
#   search_within_pages: true
#   search_full_content: true # Search full content of posts and pages
# Hi

search: false # As per requirements

atom_feed:
  hide: true # Hide RSS feed links

theme_color: "#ffffff" # Set the theme color
enable_comments: true

# # Navigation
# main:
#   - title: "About"
#     url: /about/
#   - title: "Courses"
#     url: /courses/
#   - title: "Projects"
#     url: /projects/
#   - title: "Analyses"
#     url: /analyses/

# Author info
author:
  name: "Shaswat Gupta"
  avatar: "/assets/images/shaswat.png"
  bio: "MSc in Computer Science ETH Zurich<br>IIT Bombay, Rank 1, Gold Medalist<br>ML Engineer, Ex-World Bank, Budweiser"
  location: "Zurich, Switzerland"
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/Shaswat-G"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/shaswat-gupta/"
    - label: "Substack"
      icon: "fas fa-fw fa-newspaper"
      url: "https://shazzgo.substack.com/"
    - label: "Email"
      icon: "fas fa-fw fa-envelope"
      url: "mailto:shagupta@ethz.ch"

# Social profiles for search engines
social:
  type: Person # Person or Organization
  name: "Shaswat Gupta"
  links:
    - "https://github.com/Shaswat-G"
    - "https://www.linkedin.com/in/shaswat-gupta/"
    - "https://shazzgo.substack.com/"

# Footer info
footer:
  name: "Shaswat Gupta"
  avatar: "/assets/images/shaswat.png"
  bio: "MSc in Computer Science ETH Zurich"
  location: "Zurich, Switzerland"
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/Shaswat-G"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/shaswat-gupta/"
    - label: "Substack"
      icon: "fas fa-fw fa-newspaper"
      url: "https://shazzgo.substack.com/"
    - label: "Email"
      icon: "fas fa-fw fa-envelope"
      url: "mailto:shagupta@ethz.ch"

# Plugins
plugins:
  - jekyll-feed
  - jekyll-include-cache
  - jekyll-seo-tag
  - jekyll-remote-theme
  - jekyll-sitemap

# Content settings
include:
  - _pages
  - _courses
  - _projects
  - _analyses

# Content folders
collections:
  courses:
    output: true
    permalink: /:collection/:path/
  projects:
    output: true
    permalink: /:collection/:path/
  analyses:
    output: true
    permalink: /:collection/:path/

defaults:
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true
  # _courses
  - scope:
      path: ""
      type: courses
    values:
      layout: single
      author_profile: true
      share: true
      classes: wide
      related: true
  # _projects
  - scope:
      path: ""
      type: projects
    values:
      layout: single
      author_profile: true
      share: true
      classes: wide
      related: true
  # _analyses
  - scope:
      path: ""
      type: analyses
    values:
      layout: single
      author_profile: true
      share: true
      classes: wide
      related: true
