name: Maintenance Sync

on:
  workflow_dispatch: # Manual trigger if needed
  schedule:
    - cron: "0 9 * * *" # Every day at 9 AM UTC

jobs:
  commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Configure Git
        run: |
          git config --global user.email "shagupta@ethz.ch"
          git config --global user.name "Shaswat-G"

      - name: Check for commits today
        id: check_commits
        run: |
          if git log --since=midnight --oneline | grep .; then
            echo "Commits already exist for today. Exiting."
            exit 0
          fi

      - name: Make empty commit with random message
        run: |
          messages=(
            "chore: routine maintenance"
            "ci: heartbeat check"
            "infra: sync state"
            "chore: metrics update"
            "ci: update build metadata"
            "chore: daily sync")
          msg=${messages[$RANDOM % ${#messages[@]}]}
          git commit --allow-empty -m "$msg"
          git push
